/** Default demo media per exercise, served from /public/media. */
const FILES: Record<string, string> = {
  "Goblet Squat": "cable-goblet-squat.gif",
  "Heel-Elevated Goblet Squat": "cable-goblet-squat.gif",
  "Dumbbell Squat": "cable-goblet-squat.gif",
  "Smith Machine Squat": "smith-full-squat.gif",
  "Lat Pulldown": "lat-pulldown.gif",
  "Wide-Grip Lat Pulldown": "lat-pulldown.gif",
  "Neutral-Grip Lat Pulldown": "cable-neutral-grip-lat-pulldown.gif",
  "Seated Cable Row": "cable-seated-row.gif",
  "Cable Bent Over Row": "cable-row.gif",
  "Cable Bent-Over Row": "cable-row.gif",
  "Single-Arm Cable Row": "cable-row.gif",
  "Chest-Supported Row": "dumbbell-row-with-chest-supported.png",
  "Chest-Supported Dumbbell Row": "dumbbell-row-with-chest-supported.png",
  "Single-Arm Dumbbell Row": "dumbbell-single-arm-row.mp4",
  "Dumbbell Row": "dumbbell-single-arm-row.mp4",
  "Rear Delt Fly": "dumbbell-rear-fly.png",
  "Face Pull": "cable-face-pull.gif",
  "Dumbbell Lateral Raise": "dumbbell-lateral-raise.gif",
  "Incline Dumbbell Press": "dumbbell-incline-bench-press.png",
  "Cable Triceps Pushdown": "cable-triceps-pushdown.png",
  "Single-Arm Triceps Pushdown": "cable-triceps-pushdown.png",
  "Hammer Curl": "kettlebell-standing-hammer-curl.mp4",
  "Cable Hammer Curl": "kettlebell-standing-hammer-curl.mp4",
  "Romanian Deadlift": "kettlebell-romanian-deadlift.mp4",
  "Dumbbell Romanian Deadlift": "kettlebell-romanian-deadlift.mp4",
  "Seated Leg Curl": "cable-standing-leg-curl.mp4",
  "Leg Press": "seated-leg-press.gif",
  "Single-Leg Leg Press": "seated-leg-press.gif",
  "Step Ups": "dumbbell-glute-dominant-step-up.gif",
  "Glute-Biased Step Ups": "dumbbell-glute-dominant-step-up.gif",
  "Bulgarian Split Squat": "dumbell-bulgarian-split-squat.gif",
  "Glute-Biased Bulgarian Split Squat": "dumbell-bulgarian-split-squat.gif",
  "Bodyweight Bulgarian Split Squat": "dumbell-bulgarian-split-squat.gif",
  "Smith Machine Bulgarian Split Squat": "dumbell-bulgarian-split-squat.gif",
  "Reverse / Curtsy Lunges": "single-curtsy-lunge.mp4",
  "Hip Abductor": "seated-hip-abduction.gif",
  "Single-Leg Hip Abductor": "side-hip-abduction.gif",
  "Bodyweight or Banded Hip Abduction": "side-hip-abduction.gif",
  "Glute Bridge": "heel-glute-bridge.gif",
  "Hip Thrust": "dumbbell-glute-bridge.png",
  "Smith Machine Hip Thrust": "dumbbell-glute-bridge.png",
  "Smith Machine Glute Bridge": "dumbbells-glute-bridge.png",
  "45° Glute-Biased Back Extension": "45-degree-hip-extension-glute-focused.gif",
  "Cable Kickback": "cable-diagonal-kickback.mp4",
  "Cable Kickbacks": "cable-diagonal-kickback.mp4",
};

export function defaultMedia(exerciseName: string): string | undefined {
  const file = FILES[exerciseName.trim()];
  return file ? `/media/${file}` : undefined;
}
