/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as PlanPlanIdRouteImport } from './routes/plan.$planId'
import { Route as WorkoutPlanIdDayRouteImport } from './routes/workout.$planId.$day'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanPlanIdRoute = PlanPlanIdRouteImport.update({
  id: '/plan/$planId',
  path: '/plan/$planId',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkoutPlanIdDayRoute = WorkoutPlanIdDayRouteImport.update({
  id: '/workout/$planId/$day',
  path: '/workout/$planId/$day',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/progress': typeof ProgressRoute
  '/plan/$planId': typeof PlanPlanIdRoute
  '/workout/$planId/$day': typeof WorkoutPlanIdDayRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/progress': typeof ProgressRoute
  '/plan/$planId': typeof PlanPlanIdRoute
  '/workout/$planId/$day': typeof WorkoutPlanIdDayRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/progress': typeof ProgressRoute
  '/plan/$planId': typeof PlanPlanIdRoute
  '/workout/$planId/$day': typeof WorkoutPlanIdDayRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/progress' | '/plan/$planId' | '/workout/$planId/$day'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/progress' | '/plan/$planId' | '/workout/$planId/$day'
  id: '__root__' | '/' | '/progress' | '/plan/$planId' | '/workout/$planId/$day'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProgressRoute: typeof ProgressRoute
  PlanPlanIdRoute: typeof PlanPlanIdRoute
  WorkoutPlanIdDayRoute: typeof WorkoutPlanIdDayRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan/$planId': {
      id: '/plan/$planId'
      path: '/plan/$planId'
      fullPath: '/plan/$planId'
      preLoaderRoute: typeof PlanPlanIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workout/$planId/$day': {
      id: '/workout/$planId/$day'
      path: '/workout/$planId/$day'
      fullPath: '/workout/$planId/$day'
      preLoaderRoute: typeof WorkoutPlanIdDayRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProgressRoute: ProgressRoute,
  PlanPlanIdRoute: PlanPlanIdRoute,
  WorkoutPlanIdDayRoute: WorkoutPlanIdDayRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
