/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as ThemeRouteImport } from './routes/theme'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as CustomizePlanIdRouteImport } from './routes/customize.$planId'
import { Route as PlanPlanIdRouteImport } from './routes/plan.$planId'
import { Route as WorkoutPlanIdDayRouteImport } from './routes/workout.$planId.$day'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const ThemeRoute = ThemeRouteImport.update({
  id: '/theme',
  path: '/theme',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const CustomizePlanIdRoute = CustomizePlanIdRouteImport.update({
  id: '/customize/$planId',
  path: '/customize/$planId',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanPlanIdRoute = PlanPlanIdRouteImport.update({
  id: '/plan/$planId',
  path: '/plan/$planId',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkoutPlanIdDayRoute = WorkoutPlanIdDayRouteImport.update({
  id: '/workout/$planId/$day',
  path: '/workout/$planId/$day',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/history': typeof HistoryRoute
  '/progress': typeof ProgressRoute
  '/theme': typeof ThemeRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/customize/$planId': typeof CustomizePlanIdRoute
  '/plan/$planId': typeof PlanPlanIdRoute
  '/workout/$planId/$day': typeof WorkoutPlanIdDayRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/history': typeof HistoryRoute
  '/progress': typeof ProgressRoute
  '/theme': typeof ThemeRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/customize/$planId': typeof CustomizePlanIdRoute
  '/plan/$planId': typeof PlanPlanIdRoute
  '/workout/$planId/$day': typeof WorkoutPlanIdDayRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/history': typeof HistoryRoute
  '/progress': typeof ProgressRoute
  '/theme': typeof ThemeRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/customize/$planId': typeof CustomizePlanIdRoute
  '/plan/$planId': typeof PlanPlanIdRoute
  '/workout/$planId/$day': typeof WorkoutPlanIdDayRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/history'
    | '/progress'
    | '/theme'
    | '/profile'
    | '/customize/$planId'
    | '/plan/$planId'
    | '/workout/$planId/$day'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/history'
    | '/progress'
    | '/theme'
    | '/profile'
    | '/customize/$planId'
    | '/plan/$planId'
    | '/workout/$planId/$day'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/history'
    | '/progress'
    | '/theme'
    | '/_authenticated/profile'
    | '/customize/$planId'
    | '/plan/$planId'
    | '/workout/$planId/$day'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  HistoryRoute: typeof HistoryRoute
  ProgressRoute: typeof ProgressRoute
  ThemeRoute: typeof ThemeRoute
  CustomizePlanIdRoute: typeof CustomizePlanIdRoute
  PlanPlanIdRoute: typeof PlanPlanIdRoute
  WorkoutPlanIdDayRoute: typeof WorkoutPlanIdDayRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/theme': {
      id: '/theme'
      path: '/theme'
      fullPath: '/theme'
      preLoaderRoute: typeof ThemeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/customize/$planId': {
      id: '/customize/$planId'
      path: '/customize/$planId'
      fullPath: '/customize/$planId'
      preLoaderRoute: typeof CustomizePlanIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan/$planId': {
      id: '/plan/$planId'
      path: '/plan/$planId'
      fullPath: '/plan/$planId'
      preLoaderRoute: typeof PlanPlanIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workout/$planId/$day': {
      id: '/workout/$planId/$day'
      path: '/workout/$planId/$day'
      fullPath: '/workout/$planId/$day'
      preLoaderRoute: typeof WorkoutPlanIdDayRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  HistoryRoute: HistoryRoute,
  ProgressRoute: ProgressRoute,
  ThemeRoute: ThemeRoute,
  CustomizePlanIdRoute: CustomizePlanIdRoute,
  PlanPlanIdRoute: PlanPlanIdRoute,
  WorkoutPlanIdDayRoute: WorkoutPlanIdDayRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
